
/**
* This controller is responsible for viewing meals
* It handles the following routes
* 1. /api/meals/all
* 2. /api/meals/view
* @author  Enokela Acheme Paul
* @email    achemepaulenokela@gmail.com
* @version 1.0
*/
package org.byteworks.javatest;

import java.util.HashMap;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;


@RestController
public class MealController {
    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data

    @Autowired
    private MealRepository mealRepository;

    private HashMap<String, Object> res;

    //view all meals
    @RequestMapping(value="/api/meals/all", method=RequestMethod.GET)
    public HashMap<String, Object> getAllMeals() {
        res = new HashMap<>();

        res.put("meals", mealRepository.findAll());
        return res;
    }

    /*view a particular meal
    * @param id - This is the meal id.
    */
    @RequestMapping(value="/api/meals/view", method=RequestMethod.GET)
    public HashMap<String, Object> viewMeals(@RequestParam(value = "id", required = true) int id) {
        res = new HashMap<>();
        res.put("meal", mealRepository.findById(id));
        return res;
    }

}